name:= "parse"
scalaVersion:="2.11.8"
libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "1.0.4"
libraryDependencies += "org.scalatest" %% "scalatest" % "2.2.6" % "test"
libraryDependencies += "org.apache.bcel" % "bcel" % "5.2"
libraryDependencies += "org.scalaz" %% "scalaz-core" % "7.2.4"
